<h3>MUSIK PLAYER</h3>
SELAMAT DATANG DI WEBSITE SEDERHANA MUSIC PLAYER
WEBSITE INI ADALAH WEBSITE SEDERHANA YANG SAYA BUAT UNTUK MEMPERMUDA DALAM MEMUTAR MUSIK CONTOHNYA UNTUK MENYIMPAN DAN MENCARI MUSIK YANG INGIN DI DENGARKAN.
TIDAK PERLU CEMAS MENGGUNAKAN WEBSITE SEDERHANA INI UNTUK MENDENGARKAN MUSIK
KARENA WEBSITE INI BISA MENJAGA DENGAN AMAN SEMUA MUSIK MUSIK YANG FAVORITE ANDA.